-- DML (Data Manipulation Language) : insert(입력), update(수정), delete(삭제)
-- 연습용 테이블 생성하기
CREATE TABLE DEPT_TEMP
AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP;

-- TABLE에 데이터를 추가하는 insert 문
-- INSERT INTO 테이블명(컬럼명...) VALUES(데이터...)
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC) VALUES (50, 'DATABASE', 'SEOUL');
INSERT INTO DEPT_TEMP VALUES (60, 'BACKEND', 'BUSAN');
INSERT INTO DEPT_TEMP (DEPTNO) VALUES (70);
INSERT INTO DEPT_TEMP VALUES (80, 'FRONTEND', 'INCHUN');
INSERT INTO DEPT_TEMP (DNAME, LOC) VALUES ('APP', 'DAEGU');

INSERT INTO DEPT VALUES (40, 'BACKEND', 'BUSAN'); 