CREATE TABLE FAMILY(
	FAMILY_Pos varchar2(20) PRIMARY KEY,
	F_NAME varchar2(20) NOT NULL,
	F_AGE varchar2(20) NOT NULL,
	F_HEIGHT varchar2(20) NOT NULL
	--Distinguish varchar2(20) 
);

SELECT * FROM FAMILY;

INSERT INTO FAMILY (FAMILY_POS, F_NAME, F_AGE, F_HEIGHT)
	VALUES ('아빠', '노둘리', 67, 183);
	

	
SELECT constraint_name
FROM user_constraints 
	WHERE table_name = 'FAMLIY';
	
ALTER TABLE FAMILY
DROP CONSTRAINT SYS_C007045;

ALTER TABLE FAMILY
MODIFY F_NAME NOT NULL;

ALTER TABLE FAMILY
DROP CONSTRAINT SYS_C007046;

ALTER TABLE FAMILY
MODIFY F_AGE NOT NULL;

ALTER TABLE FAMILY
DROP CONSTRAINT SYS_C007047;

ALTER TABLE FAMILY
MODIFY F_HEIGHT NOT NULL;

DROP TABLE FAMILY;

CREATE TABLE MODULE
	USER_NAME VARCHAR2(20) UNIQUE,
